# - list of names of dynamically loaded trackers
trackers : [
  "MpcTracker",
  "LineTracker",
  "LandoffTracker",
  "JoyTracker",
  "NullTracker",
  "SpeedTracker",
]

obstacle_bumper:

  enabled: true

  horizontal_distance: 1.4 # [m]
  vertical_distance: 1.0 # [m]

  # true: the drone will move away from obstacles that appear within the radius
  repulsion:

    enabled: true

    horizontal_distance: 1.3 # [m]
    horizontal_offset: 0.2 # [m] by how much to repulse from the horizontal_distance limit

    vertical_distance: 0.9 # [m]
    vertical_offset: 0.1 # [m]

rc_joystick:

  carrot_distance: 1.00 # [m]

safety:

  escalating_failsafe:

    # how often does it allow to escalate
    timeout: 2.0 # [s]
  
  rc_eland:
    action: "escalating_failsafe" # {eland, escalating_failsafe, failsafe}
