# Dense forest world
uav1:
  id: 1
  x: 3.0 
  y: 2.0 
  z: 0.0 
  heading: 3.14 

uav2:
  id: 2
  x: 0.0 
  y: 0.0 
  z: 0.0 
  heading: 0.00 
  
uav3:
  id: 3
  x: -5.0 
  y: 3.0 
  z: 0.0 
  heading: 0.00 

uav4:
  id: 4
  x: -4.0 
  y: -2.0 
  z: 0.0 
  heading: 0.00 
