# Dunes plane world
uav1:
  id: 1
  x: 10.0
  y: 2.0 
  z: 2.0
  heading: 0.0

uav2:
  id: 2
  x: 9.0
  y: 6.0
  z: 2.0 
  heading: 0.0
  
uav3:
  id: 3
  x: 5.0
  y: 8.0
  z: 2.0 
  heading: 0.0 

uav4:
  id: 4
  x: 3.0
  y: 3.0
  z: 2.0 
  heading: 0.0 
